# Generated by Django 3.0.5 on 2023-08-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_feedback_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='customer',
        ),
        migrations.AddField(
            model_name='orders',
            name='categorie',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Order Confirmed', 'Order Confirmed'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='categorie',
            field=models.CharField(choices=[('Céréale', 'Céréale'), ('Tubercule', 'Tubercule')], max_length=50, null=True),
        ),
    ]
