# Generated by Django 3.0.5 on 2023-08-23 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_auto_20230823_0744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='categorie',
        ),
    ]
